#!/bin/bash

# Скрипт для автоматического увеличения номера сборки и запуска Docker Compose
# Формат версии: MAJOR.MINOR.PATCH+BUILD

set -e

VERSION_FILE="VERSION"
COLOR_GREEN='\033[0;32m'
COLOR_BLUE='\033[0;34m'
COLOR_YELLOW='\033[1;33m'
COLOR_RED='\033[0;31m'
COLOR_RESET='\033[0m'

# Проверка существования файла VERSION
if [ ! -f "$VERSION_FILE" ]; then
    echo -e "${COLOR_RED}Ошибка: файл VERSION не найден!${COLOR_RESET}"
    echo "Создание файла VERSION с версией 0.1.0+0"
    echo "0.1.0+0" > "$VERSION_FILE"
fi

# Чтение текущей версии
CURRENT_VERSION=$(cat "$VERSION_FILE" | tr -d '\n\r')
echo -e "${COLOR_BLUE}Текущая версия: ${COLOR_YELLOW}${CURRENT_VERSION}${COLOR_RESET}"

# Разбор версии на компоненты
if [[ $CURRENT_VERSION =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)\+([0-9]+)$ ]]; then
    MAJOR="${BASH_REMATCH[1]}"
    MINOR="${BASH_REMATCH[2]}"
    PATCH="${BASH_REMATCH[3]}"
    BUILD="${BASH_REMATCH[4]}"
else
    echo -e "${COLOR_RED}Ошибка: неверный формат версии в файле VERSION${COLOR_RESET}"
    echo "Ожидаемый формат: MAJOR.MINOR.PATCH+BUILD (например, 0.1.0+0)"
    exit 1
fi

# Увеличение номера сборки
NEW_BUILD=$((BUILD + 1))
NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}+${NEW_BUILD}"

# Сохранение новой версии
echo "$NEW_VERSION" > "$VERSION_FILE"
echo -e "${COLOR_GREEN}Новая версия: ${COLOR_YELLOW}${NEW_VERSION}${COLOR_RESET}"

# Генерация файла версии для фронтенда (user-portal)
echo -e "${COLOR_BLUE}Генерация version.ts для user-portal...${COLOR_RESET}"
cat > front/user-portal/src/config/version.ts << EOF
// Auto-generated version file
// DO NOT EDIT MANUALLY - this file is generated by build.sh
export const APP_VERSION = '${NEW_VERSION}';
export const BUILD_DATE = '$(date -u +"%Y-%m-%d %H:%M:%S UTC")';
EOF

# Генерация файла версии для фронтенда (managing-portal)
if [ -d "front/managing-portal/src/config" ]; then
    echo -e "${COLOR_BLUE}Генерация version.ts для managing-portal...${COLOR_RESET}"
    cat > front/managing-portal/src/config/version.ts << EOF
// Auto-generated version file
// DO NOT EDIT MANUALLY - this file is generated by build.sh
export const APP_VERSION = '${NEW_VERSION}';
export const BUILD_DATE = '$(date -u +"%Y-%m-%d %H:%M:%S UTC")';
EOF
else
    mkdir -p front/managing-portal/src/config
    cat > front/managing-portal/src/config/version.ts << EOF
// Auto-generated version file
// DO NOT EDIT MANUALLY - this file is generated by build.sh
export const APP_VERSION = '${NEW_VERSION}';
export const BUILD_DATE = '$(date -u +"%Y-%m-%d %H:%M:%S UTC")';
EOF
fi

# Генерация файла версии для бэкенда
echo -e "${COLOR_BLUE}Генерация version.go для бэкенда...${COLOR_RESET}"
mkdir -p internal/version
cat > internal/version/version.go << EOF
package version

// Auto-generated version file
// DO NOT EDIT MANUALLY - this file is generated by build.sh

const (
	// Version - версия приложения
	Version = "${NEW_VERSION}"
	// BuildDate - дата сборки
	BuildDate = "$(date -u +"%Y-%m-%d %H:%M:%S UTC")"
	// Major - мажорная версия
	Major = "${MAJOR}"
	// Minor - минорная версия
	Minor = "${MINOR}"
	// Patch - патч версия
	Patch = "${PATCH}"
	// Build - номер сборки
	Build = "${NEW_BUILD}"
)

// GetVersion возвращает полную версию приложения
func GetVersion() string {
	return Version
}

// GetBuildDate возвращает дату сборки
func GetBuildDate() string {
	return BuildDate
}
EOF

echo -e "${COLOR_GREEN}Файлы версий сгенерированы успешно!${COLOR_RESET}"

# Экспорт переменной окружения для docker-compose
export APP_VERSION="$NEW_VERSION"

# Запуск Docker Compose
echo -e "${COLOR_BLUE}Запуск Docker Compose...${COLOR_RESET}"
echo -e "Версия приложения: ${COLOR_YELLOW}${NEW_VERSION}${COLOR_RESET}"
echo -e "Docker образы: ${COLOR_YELLOW}latest${COLOR_RESET} (версия встроена в код)"
echo ""

docker compose -f docker-compose.yml up --build

echo -e "${COLOR_GREEN}Сборка завершена!${COLOR_RESET}"
