package models

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// LiveKitWebhookEvent представляет событие webhook верхнего уровня от LiveKit
type LiveKitWebhookEvent struct {
	// Тип события
	Event     string          `json:"event"`
	// Данные комнаты (необработанный JSON)
	Room      json.RawMessage `json:"room,omitempty"`
	// Данные участника (необработанный JSON)
	Participant json.RawMessage `json:"participant,omitempty"`
	// Данные дорожки (необработанный JSON)
	Track     json.RawMessage `json:"track,omitempty"`
	// Идентификатор события
	ID        uuid.UUID       `json:"id"`
	// Время создания события
	CreatedAt string          `json:"createdAt"`
}

// Room представляет комнату LiveKit
type Room struct {
	// Внутренний уникальный идентификатор
	ID                uuid.UUID      `gorm:"type:uuid;default:gen_random_uuid()" json:"id" db:"id"`
	// ID организации, к которой относится комната
	OrganizationID    *uuid.UUID     `gorm:"type:uuid" json:"organization_id" db:"organization_id"`
	// Идентификатор сессии LiveKit
	SID               string         `gorm:"column:sid;uniqueIndex;type:varchar(255);not null" json:"sid" db:"sid"`
	// Название комнаты
	Name              string         `gorm:"type:varchar(255);not null" json:"name" db:"name"`
	// ID встречи (meeting UUID)
	MeetingID         *uuid.UUID     `gorm:"type:uuid;index" json:"meeting_id,omitempty" db:"meeting_id"`
	// Таймаут пустой комнаты в секундах
	EmptyTimeout      int            `gorm:"default:300" json:"emptyTimeout" db:"empty_timeout"`
	// Таймаут после ухода участника в секундах
	DepartureTimeout  int            `gorm:"default:20" json:"departureTimeout" db:"departure_timeout"`
	// Время создания (строка)
	CreationTime      string         `gorm:"type:varchar(50)" json:"creationTime" db:"creation_time"`
	// Время создания в миллисекундах (строка)
	CreationTimeMs    string         `gorm:"type:varchar(50)" json:"creationTimeMs" db:"creation_time_ms"`
	// Пароль TURN сервера
	TurnPassword      string         `gorm:"type:text" json:"turnPassword,omitempty" db:"turn_password"`
	// Включенные кодеки
	EnabledCodecs     []EnabledCodec `json:"enabledCodecs" gorm:"-" db:"-"`
	// Включенные кодеки в формате JSON (для БД)
	EnabledCodecsJSON string         `gorm:"column:enabled_codecs;type:jsonb;default:'[]'" json:"-" db:"enabled_codecs"`
	// Статус комнаты (active, finished)
	Status            string         `gorm:"type:varchar(50);not null;default:'active'" json:"status" db:"status"`
	// ID записи Egress (если запись активна)
	EgressID          string         `gorm:"type:varchar(255)" json:"egressId,omitempty" db:"egress_id"`
	// Время начала сессии
	StartedAt         time.Time      `gorm:"column:started_at" json:"startedAt" db:"started_at"`
	// Время завершения сессии
	FinishedAt        *time.Time     `gorm:"column:finished_at" json:"finishedAt,omitempty" db:"finished_at"`
	// Memo generated by LLM (English)
	Memo              string         `gorm:"type:text" json:"memo,omitempty" db:"memo"`
	// Memo generated by LLM (Russian translation)
	MemoRu            string         `gorm:"type:text" json:"memoRu,omitempty" db:"memo_ru"`
	// Summaries generated by LLM (JSON with both languages)
	Summaries         string         `gorm:"type:jsonb;default:'{}'" json:"summaries,omitempty" db:"summaries"`
	// Summary generation status (pending, processing, completed, failed)
	SummaryStatus     string         `gorm:"type:varchar(50);default:'pending'" json:"summaryStatus,omitempty" db:"summary_status"`
	// Summary error message (if failed)
	SummaryError      string         `gorm:"type:text" json:"summaryError,omitempty" db:"summary_error"`
	// Флаг наличия композитного видео (composite.m3u8 в корне папки комнаты)
	HasCompositeVideo bool           `gorm:"type:boolean;default:false;not null;column:has_composite_video" json:"hasCompositeVideo" db:"has_composite_video"`
	// Время создания записи в БД
	CreatedAtDB       time.Time      `gorm:"column:created_at;autoCreateTime" json:"-" db:"created_at"`
	// Время последнего обновления
	UpdatedAt         time.Time      `gorm:"column:updated_at;autoUpdateTime" json:"-" db:"updated_at"`
}

// EnabledCodec представляет кодек, включенный в комнате
type EnabledCodec struct {
	// MIME тип кодека
	Mime string `json:"mime"`
}

// Participant представляет участника комнаты LiveKit
type Participant struct {
	// Внутренний уникальный идентификатор
	ID              uuid.UUID       `gorm:"type:uuid;default:gen_random_uuid()" json:"id" db:"id"`
	// Идентификатор сессии участника LiveKit
	SID             string          `gorm:"column:sid;uniqueIndex;type:varchar(255);not null" json:"sid" db:"sid"`
	// Идентификатор сессии комнаты
	RoomSID         string          `gorm:"column:room_sid;type:varchar(255);not null" json:"-" db:"room_sid"`
	// Идентификатор пользователя
	Identity        string          `gorm:"column:identity;type:varchar(255);not null" json:"identity" db:"identity"`
	// Отображаемое имя участника
	Name            string          `gorm:"column:name;type:varchar(255)" json:"name" db:"name"`
	// Состояние участника (ACTIVE, DISCONNECTED)
	State           string          `gorm:"column:state;type:varchar(50);not null" json:"state" db:"state"`
	// Время присоединения (строка)
	JoinedAt        string          `gorm:"column:joined_at;type:varchar(50)" json:"joinedAt" db:"joined_at"`
	// Время присоединения в миллисекундах (строка)
	JoinedAtMs      string          `gorm:"column:joined_at_ms;type:varchar(50)" json:"joinedAtMs" db:"joined_at_ms"`
	// Версия протокола
	Version         int             `gorm:"column:version;default:0" json:"version" db:"version"`
	// Разрешения участника (необработанный JSON)
	Permission      json.RawMessage `gorm:"column:permission;type:jsonb" json:"permission" db:"permission"`
	// Является ли участник издателем
	IsPublisher     bool            `gorm:"column:is_publisher;default:false" json:"isPublisher,omitempty" db:"is_publisher"`
	// Причина отключения
	DisconnectReason string         `gorm:"column:disconnect_reason;type:text" json:"disconnectReason,omitempty" db:"disconnect_reason"`
	// Время выхода из комнаты
	LeftAt          *time.Time      `gorm:"column:left_at" json:"leftAt,omitempty" db:"left_at"`
	// Время создания записи в БД
	CreatedAtDB     time.Time       `gorm:"column:created_at;autoCreateTime" json:"-" db:"created_at"`
	// Время последнего обновления
	UpdatedAt       time.Time       `gorm:"column:updated_at;autoUpdateTime" json:"-" db:"updated_at"`
}

// Track представляет аудио или видео дорожку
type Track struct {
	// Внутренний уникальный идентификатор
	ID               uuid.UUID       `gorm:"type:uuid;default:gen_random_uuid()" json:"id" db:"id"`
	// Идентификатор сессии дорожки LiveKit
	SID              string          `gorm:"column:sid;uniqueIndex;type:varchar(255);not null" json:"sid" db:"sid"`
	// Идентификатор сессии участника
	ParticipantSID   string          `gorm:"column:participant_sid;type:varchar(255);not null" json:"-" db:"participant_sid"`
	// Идентификатор сессии комнаты
	RoomSID          string          `gorm:"column:room_sid;type:varchar(255);not null" json:"-" db:"room_sid"`
	// Связь с комнатой
	Room             *Room           `gorm:"foreignKey:RoomSID;references:SID" json:"room,omitempty"`
	// Тип дорожки (VIDEO, AUDIO)
	Type             string          `gorm:"column:type;type:varchar(50)" json:"type,omitempty" db:"type"`
	// Источник дорожки (MICROPHONE, CAMERA)
	Source           string          `gorm:"column:source;type:varchar(50);not null" json:"source" db:"source"`
	// MIME тип дорожки
	MimeType         string          `gorm:"column:mime_type;type:varchar(100)" json:"mimeType" db:"mime_type"`
	// Идентификатор медиа
	Mid              string          `gorm:"column:mid;type:varchar(255)" json:"mid" db:"mid"`
	// Ширина видео (для видео дорожек)
	Width            int             `gorm:"column:width;default:0" json:"width,omitempty" db:"width"`
	// Высота видео (для видео дорожек)
	Height           int             `gorm:"column:height;default:0" json:"height,omitempty" db:"height"`
	// Используется ли simulcast
	Simulcast        bool            `gorm:"column:simulcast;default:false" json:"simulcast,omitempty" db:"simulcast"`
	// Слои simulcast (необработанный JSON)
	Layers           json.RawMessage `gorm:"column:layers;type:jsonb" json:"layers,omitempty" db:"layers"`
	// Используемые кодеки (необработанный JSON)
	Codecs           json.RawMessage `gorm:"column:codecs;type:jsonb" json:"codecs,omitempty" db:"codecs"`
	// Идентификатор потока
	Stream           string          `gorm:"column:stream;type:varchar(255)" json:"stream,omitempty" db:"stream"`
	// Версия (необработанный JSON)
	Version          json.RawMessage `gorm:"column:version;type:jsonb" json:"version,omitempty" db:"version"`
	// Аудио функции
	AudioFeatures    []string        `gorm:"-" json:"audioFeatures,omitempty" db:"-"`
	// Аудио функции в формате JSON (для БД)
	AudioFeaturesJSON json.RawMessage `gorm:"column:audio_features;type:jsonb" json:"-" db:"audio_features"`
	// Политика резервного кодека
	BackupCodecPolicy string         `gorm:"column:backup_codec_policy;type:varchar(100)" json:"backupCodecPolicy,omitempty" db:"backup_codec_policy"`
	// ID записи Egress трека (если запись активна)
	EgressID          string         `gorm:"type:varchar(255)" json:"egressId,omitempty" db:"egress_id"`
	// Статус дорожки (published, unpublished)
	Status           string          `gorm:"column:status;type:varchar(50);not null" json:"status" db:"status"`
	// Время публикации
	PublishedAt      time.Time       `gorm:"column:published_at" json:"publishedAt" db:"published_at"`
	// Время отмены публикации
	UnpublishedAt    *time.Time      `gorm:"column:unpublished_at" json:"unpublishedAt,omitempty" db:"unpublished_at"`
	// Статус транскрипции (pending, processing, completed, failed)
	TranscriptionStatus string       `gorm:"column:transcription_status;type:varchar(50);default:'pending'" json:"transcription_status,omitempty" db:"transcription_status"`
	// URL результата транскрипции
	TranscriptionURL *string          `gorm:"column:transcription_url;type:text" json:"transcription_url,omitempty" db:"transcription_url"`
	// Количество фраз в транскрипции
	TranscriptionPhraseCount *int    `gorm:"column:transcription_phrase_count;type:integer" json:"transcription_phrase_count,omitempty" db:"transcription_phrase_count"`
	// Длительность транскрипции в секундах
	TranscriptionDuration *float64    `gorm:"column:transcription_duration;type:double precision" json:"transcription_duration,omitempty" db:"transcription_duration"`
	// Время создания записи в БД
	CreatedAtDB      time.Time       `gorm:"column:created_at;autoCreateTime" json:"-" db:"created_at"`
	// Время последнего обновления
	UpdatedAt        time.Time       `gorm:"column:updated_at;autoUpdateTime" json:"-" db:"updated_at"`
}

// WebhookEventLog представляет лог всех полученных событий webhook
// Сохраняет полную информацию о каждом webhook событии для аудита и отладки
type WebhookEventLog struct {
	// Уникальный идентификатор записи лога
	ID          uuid.UUID       `gorm:"type:uuid;default:gen_random_uuid();primaryKey" json:"id" db:"id"`
	// Тип события (room_started, track_published, egress_ended, и т.д.)
	EventType   string          `gorm:"column:event_type;type:varchar(100);not null;index" json:"event_type" db:"event_type"`
	// Идентификатор события от LiveKit
	EventID     string          `gorm:"column:event_id;type:varchar(255);index" json:"event_id" db:"event_id"`
	// Идентификатор комнаты (если применимо)
	RoomSID     string          `gorm:"column:room_sid;type:varchar(255);index" json:"room_sid,omitempty" db:"room_sid"`
	// Идентификатор участника (если применимо)
	ParticipantSID string       `gorm:"column:participant_sid;type:varchar(255);index" json:"participant_sid,omitempty" db:"participant_sid"`
	// Идентификатор дорожки (если применимо)
	TrackSID    string          `gorm:"column:track_sid;type:varchar(255)" json:"track_sid,omitempty" db:"track_sid"`
	// Полезная нагрузка события (необработанный JSON)
	Payload     json.RawMessage `gorm:"column:payload;type:jsonb;not null" json:"payload" db:"payload"`
	// Время создания записи
	CreatedAt   time.Time       `gorm:"column:created_at;autoCreateTime;index" json:"created_at" db:"created_at"`
}

// WebhookRequest представляет входящую полезную нагрузку webhook
type WebhookRequest struct {
	// Тип события
	Event       string                 `json:"event" binding:"required"`
	// Данные комнаты
	Room        map[string]interface{} `json:"room,omitempty"`
	// Данные участника
	Participant map[string]interface{} `json:"participant,omitempty"`
	// Данные дорожки
	Track       map[string]interface{} `json:"track,omitempty"`
	// Данные egress (для событий egress_started, egress_updated, egress_ended)
	EgressInfo  interface{}            `json:"egressInfo,omitempty"`
	// Идентификатор события
	ID          string                 `json:"id"`
	// Время создания события
	CreatedAt   string                 `json:"createdAt"`
}

// WebhookResponse представляет ответ на webhook
type WebhookResponse struct {
	// Статус обработки
	Status  string `json:"status"`
	// Сообщение о результате
	Message string `json:"message"`
}

// EgressRecording представляет запись egress (room composite или track composite)
type EgressRecording struct {
	// Уникальный идентификатор записи
	ID            uuid.UUID  `gorm:"type:uuid;default:gen_random_uuid();primaryKey" json:"id" db:"id"`
	// Идентификатор egress от LiveKit
	EgressID      string     `gorm:"column:egress_id;uniqueIndex;type:varchar(255);not null" json:"egress_id" db:"egress_id"`
	// Тип записи (room_composite, track_composite)
	Type          string     `gorm:"column:type;type:varchar(50);not null" json:"type" db:"type"`
	// Статус (started, active, ended, failed)
	Status        string     `gorm:"column:status;type:varchar(50);not null;default:'started'" json:"status" db:"status"`
	// Идентификатор комнаты
	RoomSID       string     `gorm:"column:room_sid;type:varchar(255);not null;index" json:"room_sid" db:"room_sid"`
	// Название комнаты (meeting ID)
	RoomName      string     `gorm:"column:room_name;type:varchar(255);not null;index" json:"room_name" db:"room_name"`
	// ID встречи
	MeetingID     *uuid.UUID `gorm:"type:uuid;index" json:"meeting_id,omitempty" db:"meeting_id"`
	// Идентификатор трека (для track_composite)
	TrackSID      *string    `gorm:"column:track_sid;type:varchar(255);index" json:"track_sid,omitempty" db:"track_sid"`
	// Идентификатор участника (для track_composite)
	ParticipantSID *string   `gorm:"column:participant_sid;type:varchar(255)" json:"participant_sid,omitempty" db:"participant_sid"`
	// Путь к файлу в MinIO/S3
	FilePath      string     `gorm:"column:file_path;type:text" json:"file_path,omitempty" db:"file_path"`
	// URL плейлиста HLS (для воспроизведения)
	PlaylistURL   string     `gorm:"column:playlist_url;type:text" json:"playlist_url,omitempty" db:"playlist_url"`
	// Только аудио (для room_composite)
	AudioOnly     bool       `gorm:"column:audio_only;default:false" json:"audio_only" db:"audio_only"`
	// Время начала записи
	StartedAt     time.Time  `gorm:"column:started_at;not null" json:"started_at" db:"started_at"`
	// Время завершения записи
	EndedAt       *time.Time `gorm:"column:ended_at" json:"ended_at,omitempty" db:"ended_at"`
	// Сообщение об ошибке (если failed)
	ErrorMessage  string     `gorm:"column:error_message;type:text" json:"error_message,omitempty" db:"error_message"`
	// Время создания записи в БД
	CreatedAt     time.Time  `gorm:"column:created_at;autoCreateTime" json:"created_at" db:"created_at"`
	// Время последнего обновления
	UpdatedAt     time.Time  `gorm:"column:updated_at;autoUpdateTime" json:"updated_at" db:"updated_at"`
}

// TableName переопределяет имя таблицы, используемое для Room
func (Room) TableName() string {
	return "livekit_rooms"
}

// TableName переопределяет имя таблицы, используемое для Participant
func (Participant) TableName() string {
	return "livekit_participants"
}

// TableName переопределяет имя таблицы, используемое для Track
func (Track) TableName() string {
	return "livekit_tracks"
}

// TableName переопределяет имя таблицы, используемое для WebhookEventLog
func (WebhookEventLog) TableName() string {
	return "livekit_webhook_events"
}

// TableName переопределяет имя таблицы, используемое для EgressRecording
func (EgressRecording) TableName() string {
	return "livekit_egress_recordings"
}
