# Build stage
FROM golang:1.24-alpine AS builder

ENV PATH="/go/bin:${PATH}"

WORKDIR /app

COPY go.mod go.sum* ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY . .

# Install swagger generator and refresh docs
RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN cd cmd/user-portal && \
    GOCACHE=/tmp/go-build swag init \
      --parseDependency \
      --parseInternal \
      --generalInfo main.go \
      --output docs \
      --dir . ../../internal/models

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o user-portal ./cmd/user-portal

# Runtime stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/user-portal .
COPY --from=builder /app/pkg/email/templates ./pkg/email/templates

EXPOSE 8081

CMD ["./user-portal"]
