# --- ~/.jitsi-meet-cfg/jvb/custom-jvb.conf ---

videobridge {
  apis {
    rest {
      # Эта настройка имеет наивысший приоритет и гарантированно
      # включит REST API, переопределив 'enabled = false' из основного файла.
      enabled = true
    }
  }
  websockets {
          enabled = true
          domain = "meet.recontext.online"
          tls = false
          #server-id = "172.18.0.5"
          allowed-domains = ["meet.recontext.online", "jvb"]
          server-id = "jvb-1"
      }
}