org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES=5.129.227.21:3478
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=172.18.0.4
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=185.233.186.144
org.jitsi.videobridge.rest.COLIBRI_WS_SERVER_ID=jvb-1
