// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://recontext.online/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://recontext.online/support",
            "email": "support@recontext.online"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "Аутентификация пользователя и получение JWT токена",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Вход в систему",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/password-reset/request": {
            "post": {
                "description": "Запросить код сброса пароля для отправки по электронной почте",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Запросить сброс пароля",
                "parameters": [
                    {
                        "description": "Email address",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RequestPasswordResetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RequestPasswordResetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/password-reset/reset": {
            "post": {
                "description": "Сбросить пароль пользователя с использованием проверенного кода",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Сбросить пароль с кодом",
                "parameters": [
                    {
                        "description": "Reset password data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResetPasswordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/password-reset/verify": {
            "post": {
                "description": "Проверить, что предоставленный код сброса действителен",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Проверить код сброса пароля",
                "parameters": [
                    {
                        "description": "Token ID and code",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VerifyResetCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.VerifyResetCodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/departments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить список отделов для массового выбора участников",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Helpers"
                ],
                "summary": "Список отделов для приглашений на встречи",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/files": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить постраничный список загруженных файлов пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "Список загруженных файлов",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ListFilesResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/files/permission": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Проверить, имеет ли текущий пользователь разрешение на загрузку файлов",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "Проверить разрешение на загрузку файлов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/files/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Загрузить аудио или видео файл для транскрибации (требуется разрешение на загрузку файлов)",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "Загрузить файл для транскрибации",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Audio/video file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File description",
                        "name": "description",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.FileUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/meeting-subjects": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить постраничный список активных тем встреч",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meetings"
                ],
                "summary": "Список тем встреч",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Include inactive subjects",
                        "name": "include_inactive",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MeetingSubjectsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/meetings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить постраничный список встреч, где пользователь является участником или докладчиком",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meetings"
                ],
                "summary": "Список моих встреч",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "scheduled",
                            "in_progress",
                            "completed",
                            "cancelled"
                        ],
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "presentation",
                            "conference"
                        ],
                        "type": "string",
                        "description": "Filter by type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by subject ID",
                        "name": "subject_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by date from (RFC3339 format)",
                        "name": "date_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by date to (RFC3339 format)",
                        "name": "date_to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MeetingsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создать новую встречу (требуется разрешение can_schedule_meetings или роль admin/operator)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meetings"
                ],
                "summary": "Создать новую встречу",
                "parameters": [
                    {
                        "description": "Meeting data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateMeetingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.MeetingWithDetails"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/meetings/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить детальную информацию о конкретной встрече (должен быть участником/докладчиком или администратором)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meetings"
                ],
                "summary": "Получить детали встречи",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meeting ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MeetingWithDetails"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновить информацию о встрече (должен быть создателем или администратором)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meetings"
                ],
                "summary": "Обновить встречу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meeting ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateMeetingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MeetingWithDetails"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удалить встречу (должен быть создателем или администратором)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meetings"
                ],
                "summary": "Удалить встречу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meeting ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/meetings/{meetingId}/token": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить токен доступа LiveKit для присоединения к комнате встречи (можно присоединиться за 10 минут до начала)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meetings"
                ],
                "summary": "Получить токен LiveKit для присоединения к встрече",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meeting ID",
                        "name": "meetingId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GetMeetingTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/rag/permission": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Проверить, имеет ли текущий пользователь разрешение на использование RAG поиска",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RAG"
                ],
                "summary": "Проверить разрешение на RAG",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/rag/search": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Выполнить семантический поиск с использованием RAG по транскрипциям",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RAG"
                ],
                "summary": "Семантический поиск по транскрипциям",
                "parameters": [
                    {
                        "description": "Search query",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RAGSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RAGSearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/rag/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить статистику о системе RAG",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RAG"
                ],
                "summary": "Получить статус системы RAG",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RAGStatusResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/recordings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить постраничный список записей пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Recordings"
                ],
                "summary": "Список записей пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ListRecordingsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/recordings/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Загрузить аудио или видео файл для транскрибации",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Recordings"
                ],
                "summary": "Загрузить запись",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recording title",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Audio/video file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/recordings/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить детальную информацию о конкретной записи",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Recordings"
                ],
                "summary": "Получить детали записи",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recording ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Recording"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Поиск по транскриптам с использованием семантического или ключевого поиска",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Поиск по транскриптам",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "query",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить список пользователей для выбора участников встречи",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Helpers"
                ],
                "summary": "Список пользователей для участников встречи",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить информацию о профиле пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Получить профиль пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserInfo"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновить информацию профиля пользователя (самообслуживание)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Обновить профиль пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Profile data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}/avatar": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Загрузить изображение аватара пользователя",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Загрузить аватар пользователя",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Avatar image file",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UploadAvatarResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Проверка, работает ли сервис",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitoring"
                ],
                "summary": "Проверка здоровья",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.GetMeetingTokenResponse": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer"
                },
                "forceEndAt": {
                    "type": "string"
                },
                "meetingId": {
                    "type": "string"
                },
                "participantName": {
                    "type": "string"
                },
                "roomName": {
                    "type": "string"
                },
                "scheduledAt": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.CreateMeetingRequest": {
            "type": "object",
            "required": [
                "duration",
                "scheduled_at",
                "subject_id",
                "title",
                "type"
            ],
            "properties": {
                "additional_notes": {
                    "description": "AdditionalNotes - дополнительные заметки",
                    "type": "string",
                    "example": "Подготовить отчеты"
                },
                "department_ids": {
                    "description": "DepartmentIDs - идентификаторы отделов",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"550e8400-e29b-41d4-a716-446655440000\"]"
                    ]
                },
                "duration": {
                    "description": "Duration - длительность в минутах",
                    "type": "integer",
                    "example": 60
                },
                "force_end_at_duration": {
                    "description": "ForceEndAtDuration - принудительно завершить встречу после истечения времени",
                    "type": "boolean",
                    "example": true
                },
                "needs_audio_record": {
                    "description": "NeedsAudioRecord - требуется ли аудиозапись",
                    "type": "boolean",
                    "example": true
                },
                "needs_video_record": {
                    "description": "NeedsVideoRecord - требуется ли видеозапись",
                    "type": "boolean",
                    "example": true
                },
                "participant_ids": {
                    "description": "ParticipantIDs - идентификаторы участников",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"550e8400-e29b-41d4-a716-446655440000\"]"
                    ]
                },
                "recurrence": {
                    "description": "Recurrence - частота повторения",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.MeetingRecurrence"
                        }
                    ],
                    "example": "weekly"
                },
                "scheduled_at": {
                    "description": "ScheduledAt - запланированное время начала",
                    "type": "string",
                    "example": "2025-01-15T10:00:00Z"
                },
                "speaker_id": {
                    "description": "SpeakerID - идентификатор докладчика (для презентаций)",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "subject_id": {
                    "description": "SubjectID - идентификатор темы",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "title": {
                    "description": "Title - название встречи",
                    "type": "string",
                    "example": "Еженедельное совещание"
                },
                "type": {
                    "description": "Type - тип встречи",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.MeetingType"
                        }
                    ],
                    "example": "conference"
                }
            }
        },
        "models.Department": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt - время создания отдела",
                    "type": "string"
                },
                "description": {
                    "description": "Description - описание отдела",
                    "type": "string"
                },
                "id": {
                    "description": "ID - уникальный идентификатор отдела",
                    "type": "string"
                },
                "is_active": {
                    "description": "IsActive - активен ли отдел",
                    "type": "boolean"
                },
                "level": {
                    "description": "Level - глубина в иерархии (0 для корневого)",
                    "type": "integer"
                },
                "name": {
                    "description": "Name - название отдела",
                    "type": "string"
                },
                "parent_id": {
                    "description": "ParentID - идентификатор родительского отдела (NULL для корневых отделов)",
                    "type": "string"
                },
                "path": {
                    "description": "Path - полный путь вида \"root/child/grandchild\"",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt - время последнего обновления отдела",
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code - HTTP код ошибки",
                    "type": "integer"
                },
                "error": {
                    "description": "Error - код ошибки",
                    "type": "string"
                },
                "message": {
                    "description": "Message - сообщение об ошибке",
                    "type": "string"
                },
                "timestamp": {
                    "description": "Timestamp - время возникновения ошибки",
                    "type": "string"
                }
            }
        },
        "models.FileUploadResponse": {
            "type": "object",
            "properties": {
                "file_size": {
                    "description": "FileSize - размер файла в байтах",
                    "type": "integer"
                },
                "filename": {
                    "description": "Filename - имя файла",
                    "type": "string"
                },
                "id": {
                    "description": "ID - уникальный идентификатор загруженного файла",
                    "type": "string"
                },
                "original_name": {
                    "description": "OriginalName - оригинальное имя файла",
                    "type": "string"
                },
                "status": {
                    "description": "Status - статус обработки",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TranscriptionStatus"
                        }
                    ]
                },
                "uploaded_at": {
                    "description": "UploadedAt - время загрузки",
                    "type": "string"
                }
            }
        },
        "models.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Status - статус здоровья",
                    "type": "string"
                },
                "timestamp": {
                    "description": "Timestamp - время проверки",
                    "type": "string"
                },
                "version": {
                    "description": "Version - версия сервиса",
                    "type": "string"
                }
            }
        },
        "models.ListFilesResponse": {
            "type": "object",
            "properties": {
                "files": {
                    "description": "Files - список файлов",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.UploadedFile"
                    }
                },
                "page": {
                    "description": "Page - номер текущей страницы",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "PageSize - размер страницы",
                    "type": "integer"
                },
                "total": {
                    "description": "Total - общее количество файлов",
                    "type": "integer"
                }
            }
        },
        "models.ListRecordingsResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "description": "Page - номер текущей страницы",
                    "type": "integer"
                },
                "page_size": {
                    "description": "PageSize - размер страницы",
                    "type": "integer"
                },
                "recordings": {
                    "description": "Recordings - список записей",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Recording"
                    }
                },
                "total": {
                    "description": "Total - общее количество записей",
                    "type": "integer"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "Password - пароль пользователя",
                    "type": "string",
                    "example": "password123"
                },
                "username": {
                    "description": "Username - имя пользователя или email для входа",
                    "type": "string",
                    "example": "admin@recontext.online"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "description": "ExpiresAt - время истечения срока действия токена",
                    "type": "string"
                },
                "token": {
                    "description": "Token - JWT токен аутентификации",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user": {
                    "description": "User - информация об аутентифицированном пользователе",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.UserInfo"
                        }
                    ]
                }
            }
        },
        "models.MeetingParticipantInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt - время создания записи",
                    "type": "string"
                },
                "id": {
                    "description": "ID - уникальный идентификатор участника",
                    "type": "string"
                },
                "joined_at": {
                    "description": "JoinedAt - время присоединения к встрече",
                    "type": "string"
                },
                "left_at": {
                    "description": "LeftAt - время выхода из встречи",
                    "type": "string"
                },
                "meeting_id": {
                    "description": "MeetingID - идентификатор встречи",
                    "type": "string"
                },
                "role": {
                    "description": "Role - роль участника (\"speaker\", \"participant\")",
                    "type": "string"
                },
                "status": {
                    "description": "Status - статус участника (\"invited\", \"accepted\", \"declined\", \"attended\")",
                    "type": "string"
                },
                "user": {
                    "description": "User - информация о пользователе",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.UserInfo"
                        }
                    ]
                },
                "user_id": {
                    "description": "UserID - идентификатор пользователя",
                    "type": "string"
                }
            }
        },
        "models.MeetingRecurrence": {
            "type": "string",
            "enum": [
                "none",
                "daily",
                "weekly",
                "monthly"
            ],
            "x-enum-comments": {
                "MeetingRecurrenceDaily": "Ежедневно",
                "MeetingRecurrenceMonthly": "Ежемесячно",
                "MeetingRecurrenceNone": "Не повторяется",
                "MeetingRecurrenceWeekly": "Еженедельно"
            },
            "x-enum-descriptions": [
                "Не повторяется",
                "Ежедневно",
                "Еженедельно",
                "Ежемесячно"
            ],
            "x-enum-varnames": [
                "MeetingRecurrenceNone",
                "MeetingRecurrenceDaily",
                "MeetingRecurrenceWeekly",
                "MeetingRecurrenceMonthly"
            ]
        },
        "models.MeetingStatus": {
            "type": "string",
            "enum": [
                "scheduled",
                "in_progress",
                "completed",
                "cancelled"
            ],
            "x-enum-comments": {
                "MeetingStatusCancelled": "Отменена",
                "MeetingStatusCompleted": "Завершена",
                "MeetingStatusInProgress": "Идет",
                "MeetingStatusScheduled": "Запланирована"
            },
            "x-enum-descriptions": [
                "Запланирована",
                "Идет",
                "Завершена",
                "Отменена"
            ],
            "x-enum-varnames": [
                "MeetingStatusScheduled",
                "MeetingStatusInProgress",
                "MeetingStatusCompleted",
                "MeetingStatusCancelled"
            ]
        },
        "models.MeetingSubject": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt - время создания",
                    "type": "string"
                },
                "department_ids": {
                    "description": "DepartmentIDs - отделы, с которыми связана эта тема",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "description": "Description - описание темы",
                    "type": "string"
                },
                "id": {
                    "description": "ID - уникальный идентификатор темы",
                    "type": "string"
                },
                "is_active": {
                    "description": "IsActive - активна ли тема",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name - название темы",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt - время последнего обновления",
                    "type": "string"
                }
            }
        },
        "models.MeetingSubjectsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "Items - список тем",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MeetingSubject"
                    }
                },
                "offset": {
                    "description": "Offset - смещение от начала",
                    "type": "integer"
                },
                "page_size": {
                    "description": "PageSize - размер страницы",
                    "type": "integer"
                },
                "total": {
                    "description": "Total - общее количество тем",
                    "type": "integer"
                }
            }
        },
        "models.MeetingType": {
            "type": "string",
            "enum": [
                "presentation",
                "conference"
            ],
            "x-enum-comments": {
                "MeetingTypeConference": "Совещание",
                "MeetingTypePresentation": "Доклад"
            },
            "x-enum-descriptions": [
                "Доклад",
                "Совещание"
            ],
            "x-enum-varnames": [
                "MeetingTypePresentation",
                "MeetingTypeConference"
            ]
        },
        "models.MeetingWithDetails": {
            "type": "object",
            "properties": {
                "additional_notes": {
                    "description": "AdditionalNotes - дополнительные заметки",
                    "type": "string"
                },
                "created_at": {
                    "description": "CreatedAt - время создания",
                    "type": "string"
                },
                "created_by": {
                    "description": "CreatedBy - идентификатор пользователя, создавшего встречу",
                    "type": "string"
                },
                "created_by_user": {
                    "description": "CreatedByUser - пользователь, создавший встречу",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.UserInfo"
                        }
                    ]
                },
                "departments": {
                    "description": "Departments - список отделов",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Department"
                    }
                },
                "duration": {
                    "description": "Duration - длительность в минутах",
                    "type": "integer"
                },
                "force_end_at_duration": {
                    "description": "ForceEndAtDuration - принудительно завершить встречу после истечения времени",
                    "type": "boolean"
                },
                "id": {
                    "description": "ID - уникальный идентификатор встречи",
                    "type": "string"
                },
                "livekit_room_id": {
                    "description": "LiveKitRoomID - ссылка на комнату LiveKit если встреча начата",
                    "type": "string"
                },
                "needs_audio_record": {
                    "description": "NeedsAudioRecord - требуется ли аудиозапись",
                    "type": "boolean"
                },
                "needs_video_record": {
                    "description": "NeedsVideoRecord - требуется ли видеозапись",
                    "type": "boolean"
                },
                "participants": {
                    "description": "Participants - список участников",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MeetingParticipantInfo"
                    }
                },
                "recurrence": {
                    "description": "Recurrence - частота повторения",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.MeetingRecurrence"
                        }
                    ]
                },
                "scheduled_at": {
                    "description": "ScheduledAt - запланированное время начала",
                    "type": "string"
                },
                "status": {
                    "description": "Status - текущий статус встречи",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.MeetingStatus"
                        }
                    ]
                },
                "subject": {
                    "description": "Subject - тема встречи",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.MeetingSubject"
                        }
                    ]
                },
                "subject_id": {
                    "description": "SubjectID - идентификатор темы встречи",
                    "type": "string"
                },
                "title": {
                    "description": "Title - название встречи",
                    "type": "string"
                },
                "type": {
                    "description": "Type - тип встречи",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.MeetingType"
                        }
                    ]
                },
                "updated_at": {
                    "description": "UpdatedAt - время последнего обновления",
                    "type": "string"
                }
            }
        },
        "models.MeetingsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "Items - список встреч",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MeetingWithDetails"
                    }
                },
                "offset": {
                    "description": "Offset - смещение от начала",
                    "type": "integer"
                },
                "page_size": {
                    "description": "PageSize - размер страницы",
                    "type": "integer"
                },
                "total": {
                    "description": "Total - общее количество встреч",
                    "type": "integer"
                }
            }
        },
        "models.RAGSearchRequest": {
            "type": "object",
            "required": [
                "query"
            ],
            "properties": {
                "query": {
                    "description": "Query - текст запроса",
                    "type": "string"
                },
                "threshold": {
                    "description": "Threshold - порог схожести (по умолчанию: 0.7)",
                    "type": "number"
                },
                "top_k": {
                    "description": "TopK - количество возвращаемых результатов (по умолчанию: 5)",
                    "type": "integer"
                }
            }
        },
        "models.RAGSearchResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "Count - количество найденных результатов",
                    "type": "integer"
                },
                "query": {
                    "description": "Query - исходный запрос",
                    "type": "string"
                },
                "results": {
                    "description": "Results - список результатов",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.RAGSearchResult"
                    }
                }
            }
        },
        "models.RAGSearchResult": {
            "type": "object",
            "properties": {
                "chunk_id": {
                    "description": "ChunkID - идентификатор фрагмента",
                    "type": "string"
                },
                "chunk_index": {
                    "description": "ChunkIndex - индекс фрагмента",
                    "type": "integer"
                },
                "chunk_text": {
                    "description": "ChunkText - текст фрагмента",
                    "type": "string"
                },
                "file_id": {
                    "description": "FileID - идентификатор файла",
                    "type": "string"
                },
                "file_name": {
                    "description": "FileName - имя файла",
                    "type": "string"
                },
                "similarity": {
                    "description": "Similarity - уровень схожести с запросом",
                    "type": "number"
                },
                "uploaded_at": {
                    "description": "UploadedAt - время загрузки файла",
                    "type": "string"
                }
            }
        },
        "models.RAGStatusResponse": {
            "type": "object",
            "properties": {
                "indexed_files": {
                    "description": "IndexedFiles - количество проиндексированных файлов",
                    "type": "integer"
                },
                "is_ready": {
                    "description": "IsReady - готова ли система к работе",
                    "type": "boolean"
                },
                "total_chunks": {
                    "description": "TotalChunks - общее количество фрагментов",
                    "type": "integer"
                }
            }
        },
        "models.Recording": {
            "type": "object",
            "properties": {
                "duration": {
                    "description": "Duration - длительность в секундах",
                    "type": "number"
                },
                "file_name": {
                    "description": "FileName - имя файла",
                    "type": "string"
                },
                "file_size": {
                    "description": "FileSize - размер файла в байтах",
                    "type": "integer"
                },
                "id": {
                    "description": "ID - уникальный идентификатор записи",
                    "type": "string"
                },
                "mime_type": {
                    "description": "MimeType - MIME тип файла",
                    "type": "string"
                },
                "processed_at": {
                    "description": "ProcessedAt - время завершения обработки",
                    "type": "string"
                },
                "status": {
                    "description": "Status - статус обработки записи",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.RecordingStatus"
                        }
                    ]
                },
                "storage_path": {
                    "description": "StoragePath - путь к файлу в хранилище",
                    "type": "string"
                },
                "title": {
                    "description": "Title - название записи",
                    "type": "string"
                },
                "transcript_id": {
                    "description": "TranscriptID - идентификатор транскрипции (если есть)",
                    "type": "string"
                },
                "uploaded_at": {
                    "description": "UploadedAt - время загрузки",
                    "type": "string"
                },
                "user_id": {
                    "description": "UserID - идентификатор пользователя",
                    "type": "string"
                }
            }
        },
        "models.RecordingStatus": {
            "type": "string",
            "enum": [
                "uploading",
                "queued",
                "transcribing",
                "completed",
                "failed"
            ],
            "x-enum-comments": {
                "RecordingStatusCompleted": "Завершено",
                "RecordingStatusFailed": "Ошибка",
                "RecordingStatusQueued": "В очереди",
                "RecordingStatusTranscribing": "Транскрибируется",
                "RecordingStatusUploading": "Загружается"
            },
            "x-enum-descriptions": [
                "Загружается",
                "В очереди",
                "Транскрибируется",
                "Завершено",
                "Ошибка"
            ],
            "x-enum-varnames": [
                "RecordingStatusUploading",
                "RecordingStatusQueued",
                "RecordingStatusTranscribing",
                "RecordingStatusCompleted",
                "RecordingStatusFailed"
            ]
        },
        "models.RequestPasswordResetRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "description": "Email - адрес электронной почты для отправки кода сброса",
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "models.RequestPasswordResetResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message - статусное сообщение",
                    "type": "string",
                    "example": "Password reset code sent to your email"
                },
                "token_id": {
                    "description": "TokenID - идентификатор сгенерированного токена сброса",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "models.ResetPasswordRequest": {
            "type": "object",
            "required": [
                "code",
                "new_password",
                "token_id"
            ],
            "properties": {
                "code": {
                    "description": "Code - 6-значный код подтверждения",
                    "type": "string",
                    "example": "123456"
                },
                "new_password": {
                    "description": "NewPassword - новый пароль (минимум 8 символов)",
                    "type": "string",
                    "minLength": 8,
                    "example": "newpassword123"
                },
                "token_id": {
                    "description": "TokenID - идентификатор токена сброса",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "models.ResetPasswordResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message - статусное сообщение",
                    "type": "string",
                    "example": "Password reset successfully"
                }
            }
        },
        "models.SearchResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "description": "Page - номер текущей страницы",
                    "type": "integer"
                },
                "page_size": {
                    "description": "PageSize - размер страницы",
                    "type": "integer"
                },
                "results": {
                    "description": "Results - список результатов",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SearchResult"
                    }
                },
                "total": {
                    "description": "Total - общее количество результатов",
                    "type": "integer"
                }
            }
        },
        "models.SearchResult": {
            "type": "object",
            "properties": {
                "recording_id": {
                    "description": "RecordingID - идентификатор записи",
                    "type": "string"
                },
                "relevance": {
                    "description": "Relevance - релевантность результата",
                    "type": "number"
                },
                "snippet": {
                    "description": "Snippet - фрагмент текста с совпадением",
                    "type": "string"
                },
                "timestamp": {
                    "description": "Timestamp - временная метка в секундах",
                    "type": "number"
                },
                "title": {
                    "description": "Title - название записи",
                    "type": "string"
                },
                "uploaded_at": {
                    "description": "UploadedAt - время загрузки",
                    "type": "string"
                }
            }
        },
        "models.TranscriptionStatus": {
            "type": "string",
            "enum": [
                "pending",
                "processing",
                "completed",
                "failed"
            ],
            "x-enum-comments": {
                "StatusCompleted": "Завершено",
                "StatusFailed": "Ошибка",
                "StatusPending": "Ожидает обработки",
                "StatusProcessing": "В процессе обработки"
            },
            "x-enum-descriptions": [
                "Ожидает обработки",
                "В процессе обработки",
                "Завершено",
                "Ошибка"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusProcessing",
                "StatusCompleted",
                "StatusFailed"
            ]
        },
        "models.UpdateMeetingRequest": {
            "type": "object",
            "properties": {
                "additional_notes": {
                    "description": "AdditionalNotes - дополнительные заметки",
                    "type": "string",
                    "example": "Обновленные комментарии"
                },
                "department_ids": {
                    "description": "DepartmentIDs - идентификаторы отделов",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"550e8400-e29b-41d4-a716-446655440000\"]"
                    ]
                },
                "duration": {
                    "description": "Duration - длительность в минутах",
                    "type": "integer",
                    "example": 90
                },
                "force_end_at_duration": {
                    "description": "ForceEndAtDuration - принудительно завершить встречу после истечения времени",
                    "type": "boolean",
                    "example": true
                },
                "needs_audio_record": {
                    "description": "NeedsAudioRecord - требуется ли аудиозапись",
                    "type": "boolean",
                    "example": true
                },
                "needs_video_record": {
                    "description": "NeedsVideoRecord - требуется ли видеозапись",
                    "type": "boolean",
                    "example": true
                },
                "participant_ids": {
                    "description": "ParticipantIDs - идентификаторы участников",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"550e8400-e29b-41d4-a716-446655440000\"]"
                    ]
                },
                "recurrence": {
                    "description": "Recurrence - частота повторения",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.MeetingRecurrence"
                        }
                    ],
                    "example": "weekly"
                },
                "scheduled_at": {
                    "description": "ScheduledAt - запланированное время начала",
                    "type": "string",
                    "example": "2025-01-15T10:00:00Z"
                },
                "speaker_id": {
                    "description": "SpeakerID - идентификатор докладчика",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "status": {
                    "description": "Status - статус встречи",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.MeetingStatus"
                        }
                    ],
                    "example": "in_progress"
                },
                "subject_id": {
                    "description": "SubjectID - идентификатор темы",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "title": {
                    "description": "Title - название встречи",
                    "type": "string",
                    "example": "Обновленное название"
                },
                "type": {
                    "description": "Type - тип встречи",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.MeetingType"
                        }
                    ],
                    "example": "conference"
                }
            }
        },
        "models.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "Avatar - URL аватара",
                    "type": "string",
                    "example": "https://example.com/avatar.jpg"
                },
                "bio": {
                    "description": "Bio - биография",
                    "type": "string",
                    "example": "Software developer"
                },
                "first_name": {
                    "description": "FirstName - имя",
                    "type": "string",
                    "example": "John"
                },
                "language": {
                    "description": "Language - предпочитаемый язык",
                    "type": "string",
                    "example": "en"
                },
                "last_name": {
                    "description": "LastName - фамилия",
                    "type": "string",
                    "example": "Doe"
                },
                "phone": {
                    "description": "Phone - номер телефона",
                    "type": "string",
                    "example": "+1234567890"
                }
            }
        },
        "models.UploadAvatarResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "description": "AvatarURL - URL загруженного аватара",
                    "type": "string",
                    "example": "https://example.com/avatars/user-123.jpg"
                },
                "message": {
                    "description": "Message - статусное сообщение",
                    "type": "string",
                    "example": "Avatar uploaded successfully"
                }
            }
        },
        "models.UploadResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message - статусное сообщение",
                    "type": "string",
                    "example": "File uploaded successfully"
                },
                "recording_id": {
                    "description": "RecordingID - идентификатор созданной записи",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "upload_url": {
                    "description": "UploadURL - URL для загрузки файла",
                    "type": "string",
                    "example": "https://minio:9000/recontext/uploads/550e8400-e29b-41d4-a716-446655440000.mp4"
                }
            }
        },
        "models.UploadedFile": {
            "type": "object",
            "properties": {
                "file_size": {
                    "description": "FileSize - размер файла в байтах",
                    "type": "integer"
                },
                "filename": {
                    "description": "Filename - имя файла в хранилище",
                    "type": "string"
                },
                "group_id": {
                    "description": "GroupID - идентификатор группы",
                    "type": "string"
                },
                "id": {
                    "description": "ID - уникальный идентификатор файла",
                    "type": "string"
                },
                "metadata": {
                    "description": "Metadata - дополнительные метаданные файла",
                    "type": "object",
                    "additionalProperties": true
                },
                "mime_type": {
                    "description": "MimeType - MIME тип файла",
                    "type": "string"
                },
                "original_name": {
                    "description": "OriginalName - оригинальное имя файла",
                    "type": "string"
                },
                "processed_at": {
                    "description": "ProcessedAt - время завершения обработки файла",
                    "type": "string"
                },
                "status": {
                    "description": "Status - статус обработки файла",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TranscriptionStatus"
                        }
                    ]
                },
                "storage_path": {
                    "description": "StoragePath - путь к файлу в хранилище",
                    "type": "string"
                },
                "transcription_id": {
                    "description": "TranscriptionID - идентификатор транскрипции (если есть)",
                    "type": "string"
                },
                "uploaded_at": {
                    "description": "UploadedAt - время загрузки файла",
                    "type": "string"
                },
                "user_id": {
                    "description": "UserID - идентификатор пользователя, загрузившего файл",
                    "type": "string"
                }
            }
        },
        "models.UserInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "Avatar - URL аватара или base64 изображение",
                    "type": "string",
                    "example": "https://example.com/avatar.jpg"
                },
                "bio": {
                    "description": "Bio - биография пользователя",
                    "type": "string",
                    "example": "Software developer"
                },
                "department_id": {
                    "description": "DepartmentID - идентификатор отдела, к которому принадлежит пользователь",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "email": {
                    "description": "Email - адрес электронной почты пользователя",
                    "type": "string",
                    "example": "admin@recontext.online"
                },
                "first_name": {
                    "description": "FirstName - имя пользователя",
                    "type": "string",
                    "example": "John"
                },
                "id": {
                    "description": "ID - уникальный идентификатор пользователя",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "language": {
                    "description": "Language - предпочитаемый язык пользователя",
                    "type": "string",
                    "example": "en"
                },
                "last_name": {
                    "description": "LastName - фамилия пользователя",
                    "type": "string",
                    "example": "Doe"
                },
                "permissions": {
                    "description": "Permissions - специфические разрешения пользователя",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.UserPermissions"
                        }
                    ]
                },
                "phone": {
                    "description": "Phone - номер телефона пользователя",
                    "type": "string",
                    "example": "+1234567890"
                },
                "role": {
                    "description": "Role - роль пользователя в системе",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.UserRole"
                        }
                    ],
                    "example": "admin"
                },
                "username": {
                    "description": "Username - имя пользователя для входа",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "models.UserPermissions": {
            "type": "object",
            "properties": {
                "can_approve_recordings": {
                    "description": "CanApproveRecordings - разрешение на утверждение записей",
                    "type": "boolean"
                },
                "can_manage_department": {
                    "description": "CanManageDepartment - разрешение на управление отделом",
                    "type": "boolean"
                },
                "can_schedule_meetings": {
                    "description": "CanScheduleMeetings - разрешение на планирование видеовстреч",
                    "type": "boolean"
                }
            }
        },
        "models.UserRole": {
            "type": "string",
            "enum": [
                "admin",
                "user",
                "operator",
                "service"
            ],
            "x-enum-comments": {
                "RoleService": "For service-to-service authentication"
            },
            "x-enum-descriptions": [
                "",
                "",
                "",
                "For service-to-service authentication"
            ],
            "x-enum-varnames": [
                "RoleAdmin",
                "RoleUser",
                "RoleOperator",
                "RoleService"
            ]
        },
        "models.VerifyResetCodeRequest": {
            "type": "object",
            "required": [
                "code",
                "token_id"
            ],
            "properties": {
                "code": {
                    "description": "Code - 6-значный код подтверждения",
                    "type": "string",
                    "example": "123456"
                },
                "token_id": {
                    "description": "TokenID - идентификатор токена сброса для проверки",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "models.VerifyResetCodeResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message - дополнительная информация о проверке",
                    "type": "string",
                    "example": "Code verified successfully"
                },
                "valid": {
                    "description": "Valid - валиден ли код",
                    "type": "boolean",
                    "example": true
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Recontext.online User Portal API",
	Description:      "API for users to interact with Recontext.online platform - upload recordings, view transcripts, search content",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
